services:
  app:
    build:
      context: .
    container_name: hellocat
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

env_file:
  - .env